"""Added crypto model

Revision ID: 6f9843971af2
Revises: 
Create Date: 2025-05-28 08:12:24.244132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9843971af2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_id', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('percent_change_24hrs', sa.Float(), nullable=True),
    sa.Column('percent_change_1hrs', sa.Float(), nullable=True),
    sa.Column('percent_change_7d', sa.Float(), nullable=True),
    sa.Column('price_btc', sa.Float(), nullable=True),
    sa.Column('market_cap_usd', sa.Float(), nullable=True),
    sa.Column('volume24', sa.Float(), nullable=True),
    sa.Column('volume24a', sa.Float(), nullable=True),
    sa.Column('csupply', sa.Float(), nullable=True),
    sa.Column('tsupply', sa.Float(), nullable=True),
    sa.Column('msupply', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cryptos')
    # ### end Alembic commands ###
