"""Add users, holdings, and transactions tables

Revision ID: 803c64a0f2e6
Revises: bf6708529a96
Create Date: 2025-05-28 10:56:04.346647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '803c64a0f2e6'
down_revision: Union[str, None] = 'bf6708529a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
